import { Router, Request, Response } from 'express';
import { z } from 'zod';
import { requireAuth } from '../middleware/auth';
import { requireFeature, loadEntitlementsContext } from '../middleware/entitlements';
import { requireWorkspacePermission } from '../middleware/rbac';
import { BILLING_FEATURES } from '../middleware/entitlements';
import { WORKSPACE_PERMISSIONS } from '../middleware/rbac';

const router = Router();

// Jira configuration schema
const JiraConfigSchema = z.object({
  baseUrl: z.string().url('Invalid Jira base URL'),
  email: z.string().email('Invalid email address'),
  apiToken: z.string().min(1, 'API token required'),
  projectKey: z.string().min(1, 'Project key required')
});

// Jira ticket creation schema
const JiraTicketSchema = z.object({
  config: JiraConfigSchema,
  sessionId: z.string().min(1, 'Session ID required'),
  debateResults: z.object({
    consensus: z.string(),
    dissents: z.array(z.object({
      position: z.string(),
      reasoning: z.string().optional()
    })).optional(),
    unresolved: z.array(z.string()).optional(),
    prompt: z.string().optional(),
    mode: z.string().optional()
  }),
  ticketType: z.enum(['Task', 'Story', 'Bug', 'Epic']).default('Task'),
  priority: z.enum(['Highest', 'High', 'Medium', 'Low', 'Lowest']).default('Medium'),
  assignee: z.string().optional(),
  labels: z.array(z.string()).optional(),
  customFields: z.record(z.any()).optional()
});

// Format debate results for Jira description
function formatDebateForJira(debateResults: any, sessionId: string) {
  let description = `h2. Debate Analysis Results\n\n`;
  description += `*Session ID:* ${sessionId}\n`;
  if (debateResults.prompt) {
    description += `*Original Question:* ${debateResults.prompt}\n`;
  }
  if (debateResults.mode) {
    description += `*Analysis Mode:* ${debateResults.mode}\n`;
  }
  description += `*Generated:* ${new Date().toISOString()}\n\n`;

  description += `h3. ✅ Consensus Reached\n`;
  description += `${debateResults.consensus}\n\n`;

  if (debateResults.dissents?.length > 0) {
    description += `h3. ⚠️ Dissenting Positions\n`;
    debateResults.dissents.forEach((dissent: any, index: number) => {
      description += `h4. Dissent ${index + 1}\n`;
      description += `*Position:* ${dissent.position}\n`;
      if (dissent.reasoning) {
        description += `*Reasoning:* ${dissent.reasoning}\n`;
      }
      description += `\n`;
    });
  }

  if (debateResults.unresolved?.length > 0) {
    description += `h3. 🔍 Unresolved Questions\n`;
    debateResults.unresolved.forEach((item: string) => {
      description += `* ${item}\n`;
    });
    description += `\n`;
  }

  description += `---\n`;
  description += `Generated by *SymbiosoAi ThinkTank* collaborative intelligence platform`;

  return description;
}

// Create Jira issue via REST API
async function createJiraIssue(config: any, issueData: any) {
  const auth = Buffer.from(`${config.email}:${config.apiToken}`).toString('base64');
  
  const response = await fetch(`${config.baseUrl}/rest/api/3/issue`, {
    method: 'POST',
    headers: {
      'Authorization': `Basic ${auth}`,
      'Accept': 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      fields: {
        project: {
          key: config.projectKey
        },
        summary: issueData.summary,
        description: {
          type: 'doc',
          version: 1,
          content: [
            {
              type: 'paragraph',
              content: [
                {
                  type: 'text',
                  text: issueData.description
                }
              ]
            }
          ]
        },
        issuetype: {
          name: issueData.type
        },
        priority: {
          name: issueData.priority
        },
        ...(issueData.assignee && {
          assignee: {
            emailAddress: issueData.assignee
          }
        }),
        ...(issueData.labels && issueData.labels.length > 0 && {
          labels: issueData.labels
        }),
        ...issueData.customFields
      }
    }),
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(`Jira API error: ${response.status} - ${JSON.stringify(errorData)}`);
  }

  return response.json();
}

// Test Jira connection
async function testJiraConnection(config: any) {
  const auth = Buffer.from(`${config.email}:${config.apiToken}`).toString('base64');
  
  // Test by getting project info
  const response = await fetch(`${config.baseUrl}/rest/api/3/project/${config.projectKey}`, {
    method: 'GET',
    headers: {
      'Authorization': `Basic ${auth}`,
      'Accept': 'application/json',
    },
  });

  if (!response.ok) {
    const errorData = await response.json();
    throw new Error(`Jira connection test failed: ${response.status} - ${JSON.stringify(errorData)}`);
  }

  return response.json();
}

// POST /api/jira/create-ticket - Create Jira ticket from debate results
router.post('/create-ticket',
  requireAuth,
  loadEntitlementsContext,
  requireFeature(BILLING_FEATURES.INTEGRATIONS),
  requireWorkspacePermission(WORKSPACE_PERMISSIONS.MANAGE_INTEGRATIONS),
  async (req: Request, res: Response) => {
  try {
    const parsed = JiraTicketSchema.safeParse(req.body);
    if (!parsed.success) {
      return res.status(400).json({ 
        error: 'Invalid request', 
        details: parsed.error.flatten() 
      });
    }

    const { config, sessionId, debateResults, ticketType, priority, assignee, labels, customFields } = parsed.data;

    // Generate ticket summary
    const summary = `Debate Analysis: ${debateResults.consensus.substring(0, 100)}${debateResults.consensus.length > 100 ? '...' : ''}`;
    
    // Format description
    const description = formatDebateForJira(debateResults, sessionId);

    // Create Jira issue
    const issueData = {
      summary,
      description,
      type: ticketType,
      priority,
      assignee,
      labels: labels ? [...labels, 'symbiosoai-thinktank', 'ai-analysis'] : ['symbiosoai-thinktank', 'ai-analysis'],
      customFields
    };

    const jiraResponse = await createJiraIssue(config, issueData);

    console.log(`🎫 Jira ticket created: ${jiraResponse.key} for session ${sessionId}`);

    res.json({
      success: true,
      ticketKey: jiraResponse.key,
      ticketUrl: `${config.baseUrl}/browse/${jiraResponse.key}`,
      sessionId,
      createdAt: new Date().toISOString()
    });

  } catch (error) {
    console.error('Jira ticket creation error:', error);
    res.status(500).json({
      error: 'Failed to create Jira ticket',
      message: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

// POST /api/jira/test - Test Jira connection and credentials
router.post('/test',
  requireAuth,
  loadEntitlementsContext,
  requireFeature(BILLING_FEATURES.INTEGRATIONS),
  async (req: Request, res: Response) => {
  try {
    const configParsed = JiraConfigSchema.safeParse(req.body);
    if (!configParsed.success) {
      return res.status(400).json({ 
        error: 'Invalid Jira configuration', 
        details: configParsed.error.flatten() 
      });
    }

    const config = configParsed.data;

    // Test connection
    const projectInfo = await testJiraConnection(config);

    res.json({
      success: true,
      message: 'Jira connection successful',
      project: {
        key: projectInfo.key,
        name: projectInfo.name,
        projectTypeKey: projectInfo.projectTypeKey
      },
      testedAt: new Date().toISOString()
    });

  } catch (error) {
    console.error('Jira connection test error:', error);
    res.status(400).json({
      success: false,
      error: 'Jira connection test failed',
      message: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

// GET /api/jira/issue-types/:projectKey - Get available issue types for a project
router.get('/issue-types/:projectKey',
  requireAuth,
  loadEntitlementsContext,
  requireFeature(BILLING_FEATURES.INTEGRATIONS),
  async (req: Request, res: Response) => {
  try {
    const { projectKey } = req.params;
    const { baseUrl, email, apiToken } = req.query;

    if (!baseUrl || !email || !apiToken) {
      return res.status(400).json({ 
        error: 'Missing required query parameters: baseUrl, email, apiToken' 
      });
    }

    const auth = Buffer.from(`${email}:${apiToken}`).toString('base64');
    
    const response = await fetch(`${baseUrl}/rest/api/3/issue/createmeta?projectKeys=${projectKey}&expand=projects.issuetypes`, {
      method: 'GET',
      headers: {
        'Authorization': `Basic ${auth}`,
        'Accept': 'application/json',
      },
    });

    if (!response.ok) {
      throw new Error(`Failed to fetch issue types: ${response.status}`);
    }

    const data = await response.json();
    const project = data.projects?.[0];
    
    if (!project) {
      return res.status(404).json({ error: 'Project not found' });
    }

    const issueTypes = project.issuetypes.map((type: any) => ({
      id: type.id,
      name: type.name,
      description: type.description,
      iconUrl: type.iconUrl
    }));

    res.json({
      projectKey,
      issueTypes
    });

  } catch (error) {
    console.error('Error fetching Jira issue types:', error);
    res.status(500).json({
      error: 'Failed to fetch issue types',
      message: error instanceof Error ? error.message : 'Unknown error'
    });
  }
});

export default router;