ALTER TABLE IF EXISTS orgs ADD COLUMN IF NOT EXISTS trial_start TIMESTAMP;
ALTER TABLE IF EXISTS orgs ADD COLUMN IF NOT EXISTS trial_end TIMESTAMP;
CREATE TABLE IF NOT EXISTS onboarding_progress (org_id TEXT PRIMARY KEY, steps JSONB, completed BOOLEAN DEFAULT FALSE, updated_at TIMESTAMP DEFAULT NOW());